empleados_project/empleados_app/urls.py
from django.conf.urls import url
from django.urls import path
from empleados_app import views

app_name = 'emp_app'


urlpatterns = [
  path('',views.index,name='index'),
  #path('',views.user,name='users'),
  #path('alta/',views.empleado,name='emp')
  path('media/',views.empleado,name='media'),
  path('alta/',views.empleado,name='alta_emp'),
  path('register/',views.register,name='register'),
  path('user_login/',views.user_login,name='user_login'),
]

empleados_project/empleados_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from empleados_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('emp/',include('empleados_app.urls')),
    path('admin/', admin.site.urls),
    path('media/', views.special,name='media'),
    path('special/', views.special,name='special'),
    path('logout/', views.user_logout, name='logout'),
]

empleados_project/empleados_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Empleados(models.Model):
    EMP_ID = models.IntegerField(unique=True)
    NOMBRE = models.CharField(max_length=25)
    AP_PATERNO = models.CharField(max_length=25)
    AP_MATERNO = models.CharField(max_length=25)
    TELEFONO = models.CharField(max_length=20)
    FECHA_INGRESO = models.DateField
    DEPARTAMENTO = models.CharField(max_length=264)
    SALARIO =models.IntegerField
    def __str__(self):
        return self.NOMBRE + ' '+ self.AP_PATERNO

# Create your models here.
class UserProfileInfo(models.Model):
    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option="build_ext" --global-option="--disable-jpeg"
    profile_pic = models.ImageField(upload_to='empleados_app/profile_pics',blank=True)
    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

empleados_project/empleados_app/forms.py
from django import forms
from django.contrib.auth.models import User
from empleados_app.models import Empleados, UserProfileInfo


class NewEmpForm(forms.ModelForm):
    class Meta:
        model = Empleados
        fields = '__all__'

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

empleados_project/empleados_app/views.py
from django.shortcuts import render
from empleados_app.models import Empleados
from empleados_app.forms import NewEmpForm, UserForm,UserProfileInfoForm
# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def  index(request):
    emp_list = Empleados.objects.order_by("NOMBRE")
    emp_dict = {'empleados':emp_list,'headerpage':'Lista de Empleados capturados'}
    #return render(request,'third_app/users.html',context=user_dict)
    return render(request,'empleados_app/index.html',context=emp_dict)

def empleado(request):
    form = NewEmpForm
    if request.method == "POST":
        form = NewEmpForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR IN FORM')
    return render(request,'empleados_app/empleados.html',{'form':form})

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'empleados_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'empleados_app/login.html', {})

empleados_project/templates/empleados_app/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>EMPLEADOS</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="navbar-brand red" href="{% url 'index' %}"> Consulta</a> </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'emp_app:alta_emp' %}"> Alta de Empleados</a> </li>
            <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
            <a class="nav-item nav-link" href="{% url 'emp_app:register' %}">Register</a>
            {# Some logic on what to display for last item#}
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
              <a class="nav-link" href="{% url 'emp_app:user_login' %}">Login</a>
            {% endif %}
        </ul>
      </nav>
      </div>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

empleados_project/templates/empleados_app/empleados.html
<!DOCTYPE html>
{% extends "empleados_app/base.html" %}
{% block body_block %}
      <h1> CAPTURA DE DATOS</h1>
      <h4> Ingrese los datos del Empleado</h4>
      <form  method="post"  >
        <div class="">
          {{form.as_p  }}
          {% csrf_token %}
        </div>
        <input type="submit"  class="btn btn-success" value="Submit">
      </form>
{% endblock %}

empleados_project/templates/empleados_app/empleados0.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>ACCESO A LA BASE DE DATOS EMPLEADOS</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <div class=" ">
    <div class="">
      <h1> CAPTURA DE DATOSX</h1>
      <h4> Ingrese los datos del Empleado</h4>
      <form  method="post"  >
        <div class="">
          {{form.as_p  }}
          {% csrf_token %}
        </div>
        <input type="submit"  class="btn btn-success" value="Submit">
      </form>
    </div>
    </div>


  </body>
</html>

empleados_project/templates/empleados_app/index.html
<!DOCTYPE html>
{% extends "empleados_app/base.html" %}
{% load my_extras %}

  {% block body_block %}
    <div class="jumbotron">

    <h1>{{headerpage|cut_jm:'leado'}}</h1>
  </div>
    {% if user.is_authenticated %}
    <div class="djangoTable">
      {% if empleados %}
        <table class="table table-hover">
          <thead>
            <th>NOMBRE</th>
            <th>APELLIDO PATERNO</th>
            <th>APELLIDO MATERNO</th>
            <th>TELEFONO</th>
            <th>DEPARTAMENTO</th>
          </thead>
            {% for emp in empleados %}
            <tr>
              <td>{{emp.NOMBRE}}</td>
              <td>{{emp.AP_PATERNO}}</td>
              <td>{{emp.AP_MATERNO}}</td>
              <td>{{emp.TELEFONO}}</td>
              <td>{{emp.DEPARTAMENTO}}</td>
            </tr>
            {% endfor %}
        </table>
      {% else %}
      <p>NO RECORDS FOUND</p>
      {% endif %}
    </div>
    <a href="{% url 'emp_app:alta_emp' %}">Crear nuevo empleado</a>

    {% else %}
    <h1>Nececita conectarse para poder ver los resultados</h1>
    {% endif %}
    {% endblock %}

empleados_project/templates/empleados_app/index0.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>WELCOME</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <div class="jumbotron">

    <h1>LISTA DE EMPLEADOS</h1>
  </div>

    <div class="djangoTable">
      {% if empleados %}
        <table class="table table-hover">
          <thead>
            <th>NOMBRE</th>
            <th>APELLIDO PATERNO</th>
            <th>APELLIDO MATERNO</th>
            <th>TELEFONO</th>
            <th>DEPARTAMENTOX</th>
          </thead>
            {% for emp in empleados %}
            <tr>
              <td>{{emp.NOMBRE}}</td>
              <td>{{emp.AP_PATERNO}}</td>
              <td>{{emp.AP_MATERNO}}</td>
              <td>{{emp.TELEFONO}}</td>
              <td>{{emp.DEPARTAMENTO}}</td>
            </tr>
            {% endfor %}
        </table>
      {% else %}
      <p>NO RECORDS FOUND</p>
      {% endif %}
    </div>
    <a href="{% url 'emp_app:xyz' %}">Crear nuevo usuario</a>
  </body>
</html>

empleados_project/templates/empleados_app/login.html
{% extends 'empleados_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'emp_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

empleados_project/templates/empleados_app/registration.html
{% extends "empleados_app/base.html" %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}